config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'dashboard#index'
  resources :users
  resources :candidates
  resources :companies
  get '/download_front/:id', to: "candidates#download_front", as: :download_front, format: 'docx'

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base

	# Associations
  belongs_to :user
  belongs_to :company

  has_attached_file :resume
  validates_attachment_content_type :resume, content_type: ["application/msword"]

  # Instance Methods
  def fullname
  	"#{first_name} #{last_name}"
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	respond_to :docx
	def index
		@candidates = Candidate.all
	end

	def new
		@candidate = Candidate.new
	end

	def create
		@candidate = current_user.candidates.build(candidate_params)
		if @candidate.save
			redirect_to candidates_path, notice: "Candidate created successfully."
		else
			redirect_to new_candidate_path, notice: "Something went wrong."
		end
	end

	def edit
		@candidate = Candidate.find(params[:id])
	end

	def update
		@candidate = Candidate.find(params[:id])
		if @candidate.update_attributes(candidate_params)
			redirect_to candidates_path, notice: "Candidate updated successfully."
		else
			redirect_to edit_candidate_path(@candidate), notice: "Something went wrong."
		end
	end

	def destroy
	end

	def show
	end

	def download_front
		@candidate = Candidate.find(params[:id])
		respond_to do |format|
			format.docx do
				render docx: 'download_front', filename: "#{@candidate.wpc_designation}_#{@candidate.first_name}.docx"
			end
		end
	end

	private
	def candidate_params
		params.require(:candidate).permit(:entered_date, :first_name, :last_name, :contact_number, :email, :wpc_designation, :company_id, :date_of_birth, :qualification, :experience, :current_company, :current_designation, :current_location, :open_for_location, :current_ctc, :expected_ctc, :notice_period, :reason_for_change, :reffered_for, :resume)
	end

end

app/views/candidates/download_front.docx.erb
<table border="1">
	<tr>
		<td>First Name</td>
		<td><%= @candidate.first_name %>
	</tr>
	<tr>
		<td>Last Name</td>
		<td><%= @candidate.last_name %>
	</tr>
	<tr>
		<td>Birth Date</td>
		<td><%= @candidate.date_of_birth %>
	</tr>
	<tr>
		<td>Qualification</td>
		<td><%= @candidate.qualification %>
	</tr>
	<tr>
		<td>Experience</td>
		<td><%= @candidate.experience %>
	</tr>
	<tr>
		<td>Current Company</td>
		<td><%= @candidate.current_company %>
	</tr>
	<tr>
		<td>Current Designation</td>
		<td><%= @candidate.current_designation %>
	</tr>
	<tr>
		<td>Current Location</td>
		<td><%= @candidate.current_location %>
	</tr>
	<tr>
		<td>Open For Location</td>
		<td><%= @candidate.open_for_location %>
	</tr>
	<tr>
		<td>Current CTC</td>
		<td><%= @candidate.current_ctc %>
	</tr>
	<tr>
		<td>Expected CTC</td>
		<td><%= @candidate.expected_ctc %>
	</tr>
	<tr>
		<td>Notice Period</td>
		<td><%= @candidate.notice_period %>
	</tr>
	<tr>
		<td>Reason For Change</td>
		<td><%= @candidate.reason_for_change %>
	</tr>
	<tr>
		<td>Referred For</td>
		<td><%= @candidate.reffered_for %>
	</tr>
</table>

app/views/candidates/edit.html.erb
<section class="content-header">
  <h1>
    Candidates
    <small>Edit</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= root_path %>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li><a href="<%= users_path %>"><i class="fa fa-user"></i> Candidates</a></li>
    <li class="active">Edit</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
    	<div class="box">
    		<div class="box-header">
          <h3 class="box-title">Candidate Edit</h3>
          <div class="box-tools">
            <%= link_to "<i class='fa fa-bars'></i>".html_safe, candidates_path, class: "btn btn-info btn-primary" %>
          </div>
        </div>
	    	<div class="box-body">
	    		<%= form_for @candidate, url: candidate_path, method: :patch do |f| %>
		    		<div class="form-group">
		    			<div class="row">
			    			<div class="col-md-6">
			          	<%= f.email_field :email, class: "form-control", placeholder: "Email Address" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
		    			<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
		    			<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
			        <div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :entered_date, class: "form-control", placeholder: "Entered Date" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
			        <div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :wpc_designation, class: "form-control", placeholder: "WPC Designation" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
			        <div class="row">
			    			<div class="col-md-6">
			          	<%= f.select :company_id, options_from_collection_for_select(Company.all, :id, :name), {}, class: "form-control select2" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :contact_number, class: "form-control", placeholder: "Mobile Number" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :date_of_birth, class: "form-control", placeholder: "Date of Birth" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :qualification, class: "form-control", placeholder: "Qualification" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :experience, class: "form-control", placeholder: "Experience" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :current_company, class: "form-control", placeholder: "Current Company" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :current_designation, class: "form-control", placeholder: "Current Designation" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :current_location, class: "form-control", placeholder: "Current Location" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :open_for_location, class: "form-control", placeholder: "Open For Location" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :current_ctc, class: "form-control", placeholder: "Current CTC" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :expected_ctc, class: "form-control", placeholder: "Expected CTC" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :notice_period, class: "form-control", placeholder: "Notice Period" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :reason_for_change, class: "form-control", placeholder: "Reason For Change" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :reffered_for, class: "form-control", placeholder: "Reffered For" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.file_field :resume, class: "form-control", placeholder: "Reffered For" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.submit "Update", class: "btn btn-primary" %>
			          </div>
			        </div>
		        </div>
		      <% end %>
	    	</div>
    	</div>
  	</div>
  </div>
</section>

<script type="text/javascript">
	$(".select2").select2();
</script>

app/views/candidates/index.html.erb
<section class="content-header">
  <h1>
    Candidate
    <small>List</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= root_path %>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">Candidates</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">List of Candidates</h3>
          <div class="box-tools">
            <%= link_to "<i class='fa fa-plus'></i>".html_safe, new_candidate_path, class: "btn btn-info btn-primary" %>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tbody>
              <tr>
                <th>Fullname</th>
                <th>Email</th>
                <th>Contact Number</th>
                <th>WPC Company</th>
                <th>WPC Designation</th>
                <th>Actions</th>
              </tr>
              <% @candidates.each do |candidate| %>
                <tr>
                  <td><%= candidate.fullname %></td>
                  <td><%= candidate.email if current_user.is_admin? or (current_user.is_employee? and candidate.user == current_user) %></td>
                  <td><%= candidate.contact_number if current_user.is_admin? or (current_user.is_employee? and candidate.user == current_user) %></td>
                  <td><%= candidate.try(:company).try(:name) %></td>
                  <td><%= candidate.wpc_designation %></td>
                  <td>
                    <%= link_to "<i class='fa fa-eye'></i>".html_safe, "#", class: "btn btn-info btn-primary" %>
                    <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_candidate_path(candidate), class: "btn btn-info btn-warning" %>
                    <%= link_to "<i class='fa fa-trash'></i>".html_safe, "#", class: "btn btn-info btn-danger" %>
                    <%= link_to "<i class='fa fa-download'></i>".html_safe, download_front_path(candidate), class: "btn btn-info btn-primary" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
    </div>
  </div>
</section>

app/views/candidates/new.html.erb
<section class="content-header">
  <h1>
    Candidates
    <small>Create</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= root_path %>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li><a href="<%= users_path %>"><i class="fa fa-user"></i> Candidates</a></li>
    <li class="active">New</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
    	<div class="box">
    		<div class="box-header">
          <h3 class="box-title">Add New Candidate</h3>
          <div class="box-tools">
            <%= link_to "<i class='fa fa-bars'></i>".html_safe, candidates_path, class: "btn btn-info btn-primary" %>
          </div>
        </div>
	    	<div class="box-body">
	    		<div class="row">
		        <%= render "shared/flash_messages" %>
		      </div>
	    		<%= form_for @candidate, url: candidates_path, method: :post do |f| %>
		    		<div class="form-group">
		    			<div class="row">
			    			<div class="col-md-6">
			          	<%= f.email_field :email, class: "form-control", placeholder: "Email Address" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
		    			<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :first_name, class: "form-control", placeholder: "First Name" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
		    			<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
			        <div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :entered_date, class: "form-control", placeholder: "Entered Date" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
			        <div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :wpc_designation, class: "form-control", placeholder: "Designation For" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
			        <div class="row">
			    			<div class="col-md-6">
			          	<%= f.select :company_id, options_from_collection_for_select(Company.all, :id, :name), {}, class: "form-control select2" %>
			          </div>
			        </div>
			      </div>
			      <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :contact_number, class: "form-control", placeholder: "Mobile Number" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :date_of_birth, class: "form-control", placeholder: "Date of Birth" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :qualification, class: "form-control", placeholder: "Qualification" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :experience, class: "form-control", placeholder: "Experience" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :current_company, class: "form-control", placeholder: "Current Company" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :current_designation, class: "form-control", placeholder: "Current Designation" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :current_location, class: "form-control", placeholder: "Current Location" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :open_for_location, class: "form-control", placeholder: "Open For Location" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :current_ctc, class: "form-control", placeholder: "Current CTC" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :expected_ctc, class: "form-control", placeholder: "Expected CTC" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :notice_period, class: "form-control", placeholder: "Notice Period" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :reason_for_change, class: "form-control", placeholder: "Reason For Change" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.text_field :reffered_for, class: "form-control", placeholder: "Reffered For" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.file_field :resume, class: "form-control", placeholder: "Reffered For" %>
			          </div>
			        </div>
		        </div>
		        <div class="form-group">
			       	<div class="row">
			    			<div class="col-md-6">
			          	<%= f.submit "Create", class: "btn btn-primary" %>
			          </div>
			        </div>
		        </div>
		      <% end %>
	    	</div>
    	</div>
  	</div>
  </div>
</section>

<script type="text/javascript">
	$(".select2").select2();
</script>