config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root 'dashboard#index'
  resources :users
  resources :candidates
  resources :companies
  get '/download_front/:id', to: "candidates#download_front", as: :download_front, format: 'docx'

end

app/models/company.rb
class Company < ActiveRecord::Base

	# Associations
	has_many :candidates

	# Validations
	validates :name, :address, :contact_number, :contact_person_name, :contract_start_date, :contract_end_date, :authorized_person_name, presence: true
	validate :contact_start_date_lesser_than_contract_end_date

	# Validation Methods
	def contact_start_date_lesser_than_contract_end_date
		if contract_start_date < contract_end_date
			errors.add(:contract_end_date, "can't be before Contract Start Date")
		end
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_action :set_company, only: [:edit, :update, :show, :destroy]

	def index
		@companies = Company.all
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_params)
		if @company.save
			flash.now[:success] = "Company created successfully."
			redirect_to company_path(@company)
		else
			flash.now[:danger] = @company.errors.full_messages
			render :new
		end
	end

	def edit
	end

	def update
	end

	def destroy
	end

	def show
	end

	private
	def company_params
		params.require(:company).permit(:name, :address, :contact_person_name, :contact_number, :second_contact_person_name, :second_contact_number, :contract_start_date, :contract_end_date, :authorized_person_name)
	end

	def set_company
	end
end

app/views/companies/index.html.erb
<section class="content-header">
  <h1>
    Company
    <small>List</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= root_path %>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="active">Company</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">List of Companies</h3>
          <div class="box-tools">
            <%= link_to "<i class='fa fa-plus'></i>".html_safe, new_company_path, class: "btn btn-info btn-primary" %>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tbody>
              <tr>
                <th>Name</th>
                <th>Contact Person</th>
                <th>Contact Number</th>
                <th>Contract Start Date</th>
                <th>Contract End Date</th>
                <th>Actions</th>
              </tr>
              <% @companies.each do |company| %>
                <tr>
                  <td><%= company.name %></td>
                  <td><%= company.contact_person_name %></td>
                  <td><%= company.contact_number %></td>
                  <td><%= company.contract_start_date %></td>
                  <td><%= company.contract_end_date  %></td>
                  <td>
                    <%= link_to "<i class='fa fa-eye'></i>".html_safe, "#", class: "btn btn-info btn-primary" %>
                    <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_company_path(company), class: "btn btn-info btn-warning" %>
                    <%= link_to "<i class='fa fa-trash'></i>".html_safe, "#", class: "btn btn-info btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
    </div>
  </div>
</section>

app/views/companies/new.html.erb
<section class="content-header">
  <h1>
    Companies
    <small>Create</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<%= root_path %>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li><a href="<%= companies_path %>"><i class="fa fa-user"></i> Companies</a></li>
    <li class="active">New</li>
  </ol>
</section>

<section class="content">
  <div class="box box-default">
    <div class="box-header with-border">
      <h3 class="box-title">Add New Company</h3>

      <div class="box-tools pull-right">
        <%= link_to "<i class='fa fa-bars'></i>".html_safe, companies_path, class: "btn btn-info btn-primary" %>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="row">
        <%= render "shared/flash_messages" %>
      </div>
      <div class="row">
        <%= form_for @company, url: companies_path, method: :post do |f| %>
          <div class="col-md-6">
            <div class="form-group">
              <%= f.text_field :name, class: "form-control", placeholder: "Company Name" %>
            </div>
            
            <div class="form-group">
              <%= f.text_field :contact_person_name, class: "form-control", placeholder: "Contact Person Name" %>
            </div>

            <div class="form-group">
              <%= f.text_field :second_contact_person_name, class: "form-control", placeholder: "Second Contact Person Name" %>
            </div>

            <div class="form-group">
              <div class="input-group date">
                <div class="input-group-addon">
                  <i class="fa fa-calendar"></i>
                </div>
                <%= f.text_field :contract_start_date, class: "form-control datepicker", placeholder: "Contract Start Date" %>
              </div>
            </div>

            <div class="form-group">
              <%= f.text_area :address, class: "form-control", placeholder: "Company Address", rows: "3" %>
            </div>

            <div class="form-group">
              <%= f.submit "Create", class: "btn btn-block btn-primary", style: "width: 25%;" %>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-md-6">
            <div class="form-group">
              <%= f.text_field :authorized_person_name, class: "form-control", placeholder: "Authorized Person Name" %>
            </div>
            
            <div class="form-group">
              <%= f.text_field :contact_number, class: "form-control", placeholder: "Contact Number" %>
            </div>

            <div class="form-group">
              <%= f.text_field :second_contact_number, class: "form-control", placeholder: "Second Contact Number" %>
            </div>

            <div class="form-group">
              <div class="input-group date">
                <div class="input-group-addon">
                  <i class="fa fa-calendar"></i>
                </div>
                <%= f.text_field :contract_end_date, class: "form-control datepicker", placeholder: "Contract End Date" %>
              </div>
            </div>
          </div>
          <!-- /.col -->
        <% end %>
      </div>
      <!-- /.row -->
    </div>
    <!-- /.box-body -->
  </div>
</section>

<script type="text/javascript">
  $(".datepicker").datepicker({
    autoclose: true
  });
</script>